export const SET_APP_ERROR = '@APP/SET_APP_ERROR'
export const SET_APP_LOADING = '@APP/SET_APP_LOADING'
export const SET_APP_TARIFF = '@APP/SET_APP_TARIFF'

export const SET_ERROR_TOAST = '@TOAST/SET_ERROR_TOAST'
export const SET_SUCCESS_TOAST = '@TOAST/SET_SUCCESS_TOAST'
export const HIDE_TOAST = '@TOAST/HIDE_TOAST'

export const SHOW_REQUESTFORM_MODAL = '@MODAL/SHOW_REQUESTFORM_MODAL'
export const HIDE_REQUESTFORM_MODAL = '@MODAL/HIDE_REQUESTFORM_MODAL'